# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
defaults:
  - override /optim: sgd

hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:

    # define hyperparameter search space
    params:
      data.batch_size: 16, 32
      optim.lr: 1e-1