defaults:
  - data: mnist
  - model: cnn_classifier
  - optim: adam
  - callbacks@callbacks:
      - early_stopping
      - rich_progress
  - _self_

seed: 42
precision: "high"

trainer:
  epochs: 5
  accelerator: gpu
  devices: 1

loss:
  monitor: 'val_loss'

optuna:
  name: ${data.name}
  trials: 50
