defaults:
  # Hydra configs
  - hydra: defaults
  - paths: defaults
  # Experimets configuration
  - experiment: null
  - grid: null
  - hparam_search: null
  # Defaults callbacks, can be added with:
  # train +callbacks=model_checkpoint
  - callbacks@callbacks:
      - early_stopping
      - rich_progress

  # Data and model defaults
  - data: mnist
  - model: classifier
  - optim: adam
  - override model/net: cnn
  - _self_

task_name: "train"
seed: 42
precision: "high"

trainer:
  epochs: 5
  accelerator: cpu
  devices: 1

loss:
  monitor: 'val_loss'

